name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache npm
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: |
          npm i -g lerna
          npm run bootstrap
        env:
          NPM_CONFIG_CACHE: ~/.npm
          NPM_CONFIG_PREFER_OFFLINE: 'true'
          NPM_CONFIG_SILENT: 'true'
          NPM_CONFIG_NO_AUDIT: 'true'

      - name: Build 🔧
        run: npm run build
        env:
          DEPLOY_PRIME_URL: https://rohit-gohri.github.io/
          DEPLOY_BASE_URL: /redocusaurus/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: example/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
